[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "PORT=8080 HOSTNAME=0.0.0.0 node .next/standalone/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
